services:
  - type: worker
    name: eko-metropolis-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: COMMAND_PREFIX
        value: "!"
      - key: DB_PATH
        value: ekobot.db
